// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAPSqV-lSuQQGqPuLp4OiKtW06UgL-Dvo',
    appId: '1:780033586360:web:ee021065ca562e54c6304d',
    messagingSenderId: '780033586360',
    projectId: 'facebook-login-42778',
    authDomain: 'facebook-login-42778.firebaseapp.com',
    storageBucket: 'facebook-login-42778.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAf5PbAeK58Um-wa4El6OogI7l-Ar8IQv8',
    appId: '1:780033586360:android:a80c16de4080a010c6304d',
    messagingSenderId: '780033586360',
    projectId: 'facebook-login-42778',
    storageBucket: 'facebook-login-42778.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzHx-y1A3igwil4tISvGi98BWzX8xsm1c',
    appId: '1:780033586360:ios:82d48f65b0f7ad21c6304d',
    messagingSenderId: '780033586360',
    projectId: 'facebook-login-42778',
    storageBucket: 'facebook-login-42778.firebasestorage.app',
    androidClientId:
        '780033586360-vv6tpagle32a0rq237n7c2r70h1rgl1u.apps.googleusercontent.com',
    iosClientId:
        '780033586360-d7v7unbo1uh1h607kil3i0qqul1rbqi0.apps.googleusercontent.com',
    iosBundleId: 'com.example.getxApi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzHx-y1A3igwil4tISvGi98BWzX8xsm1c',
    appId: '1:780033586360:ios:82d48f65b0f7ad21c6304d',
    messagingSenderId: '780033586360',
    projectId: 'facebook-login-42778',
    storageBucket: 'facebook-login-42778.firebasestorage.app',
    androidClientId:
        '780033586360-vv6tpagle32a0rq237n7c2r70h1rgl1u.apps.googleusercontent.com',
    iosClientId:
        '780033586360-d7v7unbo1uh1h607kil3i0qqul1rbqi0.apps.googleusercontent.com',
    iosBundleId: 'com.example.getxApi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDAPSqV-lSuQQGqPuLp4OiKtW06UgL-Dvo',
    appId: '1:780033586360:web:6b44a2c6f20ea367c6304d',
    messagingSenderId: '780033586360',
    projectId: 'facebook-login-42778',
    authDomain: 'facebook-login-42778.firebaseapp.com',
    storageBucket: 'facebook-login-42778.firebasestorage.app',
  );
}
